### ISSUE TITLE
To create a github page for web development resources

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/Ultimate-Web-Development-Resources#138]
To create a github page for this repostitory to view all the resources and also the projects

**Comment by prakharbhardwaj1504** [comment]
I will deliver it up to your expectation, kindly assign...

**Comment by Prince-2204** [comment]
Can I Work on the Same Project ? I have experience of building fully responsive web pages .

**Comment by epicadidash** [comment]
Assigned . You can start work .
@prakharbhardwaj1504 and @Prince-2204 Please communicate and work together

**Comment by Prince-2204** [comment]
ok sure.

**Comment by Prince-2204** [comment]
@prakharbhardwaj1504 lets make it together.

**Comment by DhanushNehru** [comment]
Looking forward for your contribution @Prince-2204 @prakharbhardwaj1504 

All the best

**Comment by Prince-2204** [comment]
Surely We will do it.

**Comment by DhanushNehru** [comment]
Any updates on this @Prince-2204 @prakharbhardwaj1504 ?

**Comment by DhanushNehru** [comment]
https://dhanushnehru.github.io/Ultimate-Web-Development-Resources
