### ISSUE TITLE
[Documentation] Use proper names instead of resources 

### ISSUE THREAD

**Issue by smty2018** [DhanushNehru/Ultimate-Web-Development-Resources#139]
Want to change to proper resource names instead of just resources so that it is easier for the user to understand.
![image](https://github.com/DhanushNehru/Ultimate-Web-Development-Resources/assets/74114936/0531c2ff-f673-4998-b9c4-f0f27ec0b52d)

**Comment by DhanushNehru** [comment]
Sure @smty2018
