### ISSUE TITLE
Myntra Customize - Scroll to Top Button

### ISSUE THREAD

**Issue by HarineMurugan** [DhanushNehru/Ultimate-Web-Development-Resources#145]
Add a button scroll to top
On clicking this, the page should scroll to the top.

**Comment by HarineMurugan** [comment]
Can you please assign this to me?

**Comment by epicadidash** [comment]
Done ✅ @HarineMurugan !! 
You can start working right away

**Comment by epicadidash** [comment]
Completed by @HarineMurugan
