### ISSUE TITLE
Want to add a site for Web Images

### ISSUE THREAD

**Issue by shivanshi-s** [DhanushNehru/Ultimate-Web-Development-Resources#16]
Hi Dhanush, saw this repository on twitter. 
I want to add 'undraw' as a site for web images and photos. 
Let me know if it is open for contributions!

**Comment by DhanushNehru** [comment]
Hey @shivanshi-s 

Yes you can add 🙂

**Comment by shivanshi-s** [comment]
Thank you! Will make a pr soon :)

**Comment by shivanshi-s** [comment]
actually it should be under illustrations, will put it there
