### ISSUE TITLE
I want to add scannable QR code  generator

### ISSUE THREAD

**Issue by Anju-Narnolia** [DhanushNehru/Ultimate-Web-Development-Resources#187]
@DhanushNehru Please assign me this issue with the hacktoberfest tag.

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me

**Comment by Shivangi015** [comment]
hey @DhanushNehru please assign this issue to me

**Comment by 2021eo3ar** [comment]
Hello @DhanushNehru  please assign me this issue, I can add a good value.

**Comment by DhanushNehru** [comment]
Hi @2021eo3ar @Anju-Narnolia @Shivangi015 @Kedarnath-Rothe make sure your codes are different & let all your projects be as subfolders as **QR Code Generator 1** , **QR Code Generator 2** and so ..  with **QR code generator** as the main folder

**Comment by 2021eo3ar** [comment]
Hey, @DhanushNehru I have merged the PR please review it and tell me if I have to fix anything.
Can you also label it as Hacktoberfest-accepted, if it is correct.

**Comment by 2021eo3ar** [comment]
Please review my PR once, I have put a lof of efforts in it.
