### ISSUE TITLE
Under HTML Learning Resources section rename the resource name instead of numbers

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/Ultimate-Web-Development-Resources#197]

**Comment by adarshpathak3408** [comment]
Please assign this issue to me with the "Hacktober Fest" label

**Comment by luv2027** [comment]
Heya @DhanushNehru  I would like to work on this issue.

**Comment by himanchal08** [comment]
i would like to work on this issue it seems
i will try my best to implement it
i don't have much idea of code so i'll need help
if you think i can do the job please assign it to me i do have basic knowledge of html css and js
