### ISSUE TITLE
Can I add number guessing effect with sound effects |HTML|CSS|JS

### ISSUE THREAD

**Issue by Khushi-74** [DhanushNehru/Ultimate-Web-Development-Resources#205]
please assign me this under hactoberfest 2023 @DhanushNehru

**Comment by DhanushNehru** [comment]
Sure @Khushi-74

**Comment by Khushi-74** [comment]
thank you @DhanushNehru #213 completed

**Comment by sakshams23** [comment]
Please assign me with this issue I want to contribute @DhanushNehru
