### ISSUE TITLE
Netflix UI Clone only using HTML and CSS

### ISSUE THREAD

**Issue by AaadityaG** [DhanushNehru/Ultimate-Web-Development-Resources#210]
This will be fully responsive and made from scratch

![Netflix — Mozilla Firefox 25-07-2023 03_56_43 PM](https://github.com/DhanushNehru/Ultimate-Web-Development-Resources/assets/114663382/2124632f-9347-4002-aa0d-5f9d5641fe00)

**Comment by Adi-456** [comment]
Kindly assign this task to me.
