### ISSUE TITLE
Add Aeroplane Game

### ISSUE THREAD

**Issue by sujitmahapatra** [DhanushNehru/Ultimate-Web-Development-Resources#256]
**Description**
The Aeroplane Game is a fun and interactive web-based game where you control an aeroplane's flight. Your objective is to fly the aeroplane for as long as possible while maintaining control and skill. The game offers an exciting challenge for players to test their flying skills.

**Tech Stack**
- HTML
- CSS
- JavaScript

 👉 **[Live Demo](https://sm-aeroplane-game.netlify.app)**

**Comment by DevanshKyada27** [comment]
Hey @DhanushNehru can you please assign this issue to me looks amazing and want to work on it.

**Comment by DevanshKyada27** [comment]
Hey @DhanushNehru can you please merge this PR.

**Comment by DevanshKyada27** [comment]
Hey @DhanushNehru @Swpn0neel you can merge the PR #456. :)
