### ISSUE TITLE
update readme.md file

### ISSUE THREAD

**Issue by Anju-Narnolia** [DhanushNehru/Ultimate-Web-Development-Resources#267]
Add contributor guidelines :
All git commands serial-wise that are used for contribution.

**Comment by Swpn0neel** [comment]
Great, you can start working on that!!

**Comment by Anju-Narnolia** [comment]
@Swpn0nee Where should I add my code (git commands) in readme.md or contributing.md?

**Comment by DhanushNehru** [comment]
Hi @Anju-Narnolia contributing guidelines are already added so closing this issue
