### ISSUE TITLE
To add instruction of playing on dice game 

### ISSUE THREAD

**Issue by harshita-2003** [DhanushNehru/Ultimate-Web-Development-Resources#286]
Currently one can just open the game and has no idea what to do next 

will add instruction on the page

**Comment by Archie200** [comment]
I would like to work on this. Please add hacktober fest label on this issue @harshita-2003

**Comment by selemondev** [comment]
This issue has been resolved by @harshita-2003 using pull request number #287 . Thank you @harshita-2003 and @Archie200 for your contributions.
