### ISSUE TITLE
Updating README.md

### ISSUE THREAD

**Issue by kishanrajput23** [DhanushNehru/Ultimate-Web-Development-Resources#292]
I have gone through the all `README.md` file content and I thought I can add a new `category` called `YouTube Channels To Learn Web Development` as there are a lot of resources also available on youtube which can help many folks to get started with web dev.

If you find this idea useful then you can assign this issue to me or if you want to add some other changes then also let me know, I'll do that also.

**Comment by DhanushNehru** [comment]
HI @kishanrajput23 we already have a section 'free yourtube resources'
