### ISSUE TITLE
Make list of projects table better in readme

### ISSUE THREAD

**Issue by DhanushNehru** [DhanushNehru/Ultimate-Web-Development-Resources#302]
Please make the list of projects table in form of three or four columns.
Also make sure the contents are in alphabetical order

Add if any projects are missed

Example
|         |            |      | |
|--------------------|------------------|---------------|-----------|
| Blog Website   | Bloggers Website     | Calculator         | Chess        | 
| City Finder         | Clock Project    | DRUM KIT       | Dice Challenge |

**Comment by kishanrajput23** [comment]
hey can I work on this issue.

**Comment by selemondev** [comment]
Thanks @kishanrajput23 for working on this 😄.

Closes #306
