### ISSUE TITLE
Adding temperature convertor 

### ISSUE THREAD

**Issue by DivyanshiNarang** [DhanushNehru/Ultimate-Web-Development-Resources#316]
I can add a temperature convertor built using HTML, CSS, and Javascript with a good UI.

**Comment by selemondev** [comment]
Go ahead and :

1. Build it.

2. Add it in the README.md file

3. Create a pull request.

**Comment by vaishnavisingh20** [comment]
#340 I have created a pull request for temperature converter, please review and merge it @DhanushNehru

**Comment by DivyanshiNarang** [comment]
Hello @DhanushNehru , @selemondev as I was working on this issue. I have created a pull request. Please review it.
