### ISSUE TITLE
modify js of calculator 

### ISSUE THREAD

**Issue by SoulNikhar** [DhanushNehru/Ultimate-Web-Development-Resources#324]
@DhanushNehru  I want to modify the JavaScript of Calculator 
https://github.com/DhanushNehru/Ultimate-Web-Development-Resources/tree/main/calculator
can I do it ?

**Comment by SoulNikhar** [comment]
@DhanushNehru  I already commit my modified js script for calculator. Please verify it and merger my PR

**Comment by selemondev** [comment]
@SoulNikhar I have reviewed your PR and merged it. Thank you for your contribution 🔥.
