### ISSUE TITLE
Adding Love caluculator

### ISSUE THREAD

**Issue by mahendrameghwal** [DhanushNehru/Ultimate-Web-Development-Resources#333]
i want to add my love calculator website
The Love Calculator provides a score from 0% to 100% that is meant to be an indication of a match in terms of love, based on the names of two people. The higher the percentage, the better the match to this website any person can find easy their relationship.

**Comment by alpha2207** [comment]
Hey @DhanushNehru, I would like to work on this. I already have deployed the same project ( Link: https://alpha2207.github.io/lovecalci/). If possible assign me this. I can complete this in a single day.

**Comment by alpha2207** [comment]
Hey @DhanushNehru, Just made a pr adding the love calculator. Please check once ( https://github.com/DhanushNehru/Ultimate-Web-Development-Resources/pull/386).

**Comment by selemondev** [comment]
Thanks for your contribution @alpha2207 and @mahendrameghwal for suggesting the project. This issue has been successfully resolved by @alpha2207 in pull request #386 🔥.
