### ISSUE TITLE
Online Restaurant Website

### ISSUE THREAD

**Issue by rittikadeb** [DhanushNehru/Ultimate-Web-Development-Resources#376]
## Description

This is a simple website designed to provide a seamless user experience for customers looking to view the menu, location, and place orders online. The website is optimized for desktop as well as mobile, ensuring that it is easily accessible to all users.

## Features

- Browse the menu
- View the food gallery 
- View hours of operation and contact information

## Stacks Used
* HTML  
* CSS
* JavaScript

**Comment by rittikadeb** [comment]
Please assign me this issue under Hacktoberfest tag.

**Comment by nikhilaPuvvula** [comment]
could you please assign me this issue under hacktoberfest tag

**Comment by rittikadeb** [comment]
@DhanushNehru pls assign me this issue

**Comment by dpvasani** [comment]
Assign to me
