### ISSUE TITLE
Add TicTacToe Game

### ISSUE THREAD

**Issue by predator3813** [DhanushNehru/Ultimate-Web-Development-Resources#442]
I want to Add TicTacToe Game . Please assign this issue to me.

**Comment by DevanshKyada27** [comment]
Hey @DhanushNehru @Swpn0neel can you please assign this issue to me.
Want to work on it.

**Comment by DevanshKyada27** [comment]
Hey @DhanushNehru @Swpn0neel @selemondev created a PR.
Hope you like it.
Looking forward for merging it. :)

**Comment by AnshuWorld** [comment]
Please assign me this work
