### ISSUE TITLE
Add YouTube resources for web development.

### ISSUE THREAD

**Issue by AnuragSharma122** [DhanushNehru/Ultimate-Web-Development-Resources#57]
Please assign this issue to me.
Also, add hactoberfest label to this issue.

**Comment by SattyamSamania** [comment]
Hey @DhanushNehru if the issue is still open can I work on this under Hacktoberfest contribution?

**Comment by Mansi782** [comment]
please assign this issue to me i would like to work on this

**Comment by Mansi782** [comment]
please assign this issue to me i would like to work on this

**Comment by anushka9555** [comment]
Hello @DhanushNehru can I work on this issue?
