### ISSUE TITLE
Can i contribute on free youtube resources ?

### ISSUE THREAD

**Issue by Brymmobaggins** [DhanushNehru/Ultimate-Web-Development-Resources#65]

**Comment by Prince-2204** [comment]
I am interested in contributing in this. can you please give a description what to do.

**Comment by DhanushNehru** [comment]
You must mention popular youtube channels for learning web development resources, if anything left out

**Comment by Prince-2204** [comment]
ok sure i will do that.

**Comment by Prince-2204** [comment]
@DhanushNehru I have made a pull request please review it.

**Comment by Mansi782** [comment]
i am also intereseted in contirbuting to this ,please assign this to me

**Comment by anushka9555** [comment]
I am interested in contributing. Please assign me this task

**Comment by Tooba-Amjad** [comment]
I am also interested .Kindly assigned this to me

**Comment by itssiddhantjain** [comment]
@DhanushNehru I am interested please assign me this issue
